name: raking_IPF
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - altair
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - openpyxl
  - pandas
  - pytorch
  - scipy
  - torchvision


